### ISSUE TITLE
Commit access for upstream

### ISSUE THREAD

**Issue by eszlari** [flathub/io.github.jliljebl.Flowblade#3]
@nedrichards @TingPing Could you give @jliljebl commit access?

**Comment by TingPing** [comment]
Invited.

**Comment by jliljebl** [comment]
thanks.

**Comment by eszlari** [comment]
@TingPing Could you send another invitation?

**Comment by TingPing** [comment]
Invites can be found here: https://github.com/flathub/io.github.jliljebl.Flowblade/invitations

**Comment by eszlari** [comment]
Why is @jliljebl not a `Collaborator`?

**Comment by TingPing** [comment]
Because they never clicked accept.

**Comment by jliljebl** [comment]
Ok, thank you, i now clicked on the invite button and should have commit
access to Flowblade Flathub repository.
